---
title: La confidentialité différentielle
subtitle: |
  **[Appliquée via un outil de requêtage]{.orange}**
author: Stuart BENOLIEL
date: today
slide-number: true
lang: fr
chalkboard: # press the B key to toggle chalkboard
  theme: whiteboard
format:
  onyxia-revealjs:
    output-file: index.html
editor:
  render-on-save: true
---

## Pourquoi de nouvelles méthodes de protection ?

- Obligation légale : [Loi de 1951]{.orange} et [RGPD (2018)]{.orange} imposent à la statistique publique de protéger les données individuelles

. . .

- Les méthodes traditionnelles sont insuffisantes : agrégation ou blanchiment des cellules, mais...

. . .

- [Complexité]{.orange} des règles de diffusion sur certaines sources (Fidéli, ...)

. . .

- Adaptées seulement à une diffusion [centralisée unique]{.orange}


## La confidentialité différentielle : un nouveau paradigme

<br>

- Un cadre [mathématique rigoureux]{.orange} offrant des [garanties formelles]{.orange} de protection, indépendantes des connaissances de l’attaquant

. . .

- [Quantification]{.orange} de la perte de confidentialité

. . .

- Adaptée à une diffusion [décentralisée multiple]{.orange}


##  La confidentialité différentielle : un nouveau paradigme

<br>

- Un cadre [mathématique rigoureux]{.orange} **(et contraignant)** offrant des [garanties formelles]{.orange} de protection, indépendante des connaissances de l’attaquant

<!-- spacer -->

- [Quantification]{.orange} **abstraite** de la perte de confidentialité

<!-- spacer -->

- Adaptée à une diffusion [décentralisée multiple]{.orange} **mais nécessite gouvernance et arbitrage**

# Présentation de l’outil

## Et maintenant ?

<br>

- Nécessité d’un [cadre de diffusion clair]{.orange} : quel budget ? qui arbitre ?

. . .

- Besoin d'[approfondissements méthodologiques]{.orange} (choix des bornes *L* et *U*, ajout de nouveaux indicateurs, ...)

. . .

- [Formation et sensibilisation]{.orange} des utilisateurs

# Merci pour votre attention !


::: {.notes}
Plan de présentation :
- Rappel du mécanisme d’ajout de bruit
- Focus sur les quantiles et leur protection via le mécanisme exponentiel
- Mise en application sur un dataset réel
- Introduction des poids de priorité
- Illustration du gain via la dépendance entre requêtes

Questions à préparer :
- Fonctionnalité de suivi avancé de budget mise de côté après échanges avec Lomas (statisticiens suisses)
- Retours de chargés d’étude : demande de simplicité et d’utilisabilité
- Exemple concret difficile à figer (choix du budget, dépendance à la taille d’échantillon)
- Argumenter la complexité vs le gain pour les totaux
- Justifier le choix des MCG pour le débruitage
- Montrer un exemple de brèche possible (attaque d’inférence) avec méthode suppressive
- Quelles métriques seraient publiables par l’Insee au final ?
- Revoir certaines hypothèses techniques sur les mécanismes (MCG,  etc.)

- Lomas -->> Réunion préparée avec des statisticiens Suisses ayant participé au projet. A la suite de cette réunion, choix de laisser cette fonctionnalité avancée de suivi avancée de budget de coté
- Pris contact aves des chargés d'études -->> Coeur du projet de prendre en compte cette aspect, mais surtout d'abord objectif d'appliquer concrètement la CD, on est à un stade de POC
- Exemple d'application concret -->> En toute honnêteté, c'est un véritable manque. Justifications : manque de temps et difficulté à prendre un exemple d'étude qui pourrait être représentative (dépendance de la taille de l'échantillon) + choix du budget
- Complexité des mécanismes pour le total compensé par un gain ? -->> savoir argumenter
- Défendre le choix de débruiter
- Montrer un exemple de brèche possible (attaque d’inférence) avec méthode suppressive
- Quelles métriques seraient publiables par l’Insee au final ?
- Revoir certaines hypothèses techniques sur les mécanismes (MCG,  etc.)
- Explication de la composition parallèle
:::
